using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public enum EPerkType
{
	NONE = -1, COLLECTOR, MONSTERPUSH, MONSTERCORNERING, DESTROYBARRICADE, PLATFORM_STEPS, LOOTER, PROSPECTOR, ARROWRUSH, INVULNERABILITY,
	DAMAGESURPLUS, MELEEATTACK, RANGEDATTACK, MAGICATTACK, MOVEMENTLEVEL, ARROWWALKING, DEXTERITY, NOTHING, ORBSTRIKER, 
    COOPERATION, MELEESHIELD, MISSILESHIELD, MAGICSHIELD, SCOUT, STAR, PLATFORMWALKING, AMBUSHER, WALLDESTROYER, BARRICADE, MEMORY, TOOLBOX,
    SPRINTERLEVEL, FIREMASTERLEVEL, BERSERKLEVEL, RICOCHETLEVEL, BEEHIVETHROWERLEVEL, PSYCHICLEVEL, SNEAKINGLEVEL, BARRICADEFIGHTERLEVEL, EVASIONLEVEL,
    PERFECTIONISTLEVEL, SCAVENGERLEVEL, AGILITYLEVEL, ARROWFIGHTERLEVEL, ARROWINLEVEL, ARROWOUTLEVEL, FRESHATTACKLEVEL, RISKYATTACKLEVEL,
    MORTALJUMPLEVEL, OPENFIELDATTACKLEVEL, INTELLIGENCELEVEL, INTEL_THREAT, INTEL2, INTEL3, INTEL4, BASETHREATDURATION, BASEFREEEXITHPLIMIT, 
    FIREPOWERLEVEL, FIRESPREADLEVEL, FIREWOODNEEDED, OUTSIDEFIREWOODALLOWED, FIREPITSNEEDEDFORDISCOUNT, FREEPLATFORMEXIT, OUTAREABURNINGBARRICADEDESTROYBONUS,
    OVERBARRICADESCOUT, SHOWRESOURCECHANCE, SHOWRESOURCENEIGHBORSCHANCE, BARRICADEFORRUNE, SCARYLEVEL, HERONEIGHBORTOUCHADDER, FIRESTARBONUS, RESOURCEPERSISTANCE, 
    ECONOMY, RTMELEEATTACKSPEED, RTRANGEDATTACKSPEED, MIRE, RESTDISTANCE, SLAYERLEVEL, FLYINGTARGETTING, SLAYERANGLE, SLAYERMAXHP, DISGUISE,
    DRAGONBONUSDROP, DRAGONBARRICADEPROTECTION, MINING, FISHING, FISHING_1, FISHING_2, FISHING_3, FISHING_4
}

public class Perk : MonoBehaviour
{
	public EPerkType Type;
    public Artifact.ECategory Category;
    public tk2dSprite UIIconSprite, UIIconBackSprite;
    public string TitleText, MainText;
    public int UiPanelPerkID;
    public tk2dUIItem UIButton;
    public Artifact Artifact;
	public tk2dTextMesh AmountText;
	public UILabel Label;
	public UIButton Button;
	public UI2DSprite[] Sprite;
    public bool ActivateIcon = true;
    public bool ResizeIcon = true;
    public  bool UseGoogle = true;
    public  bool HasBigHelpText = false;
    public  bool ShowSkill = true;
    public void SelectPerk()
    {
		//if( UI.I.SelectedPerk != EPerkType.NONE )
		//	if( UiPanelPerkID == UI.I.SelectedPerk )
		//	{
		//		UI.I.SelectedPerk = -1;
		//		return;
		//	}

		//UI.I.SelectedPerk = UiPanelPerkID;
    }

    public void Copy( Perk pk )
    {
    UIIconSprite     = pk.UIIconSprite;
    UIIconBackSprite = pk.UIIconBackSprite;
    TitleText        = pk.TitleText;
    MainText         = pk.MainText;
    UiPanelPerkID    = pk.UiPanelPerkID;
    Category         = pk.Category;
    }
}
