//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;




//3 front rows code
//Vector2 zl = ( Map.I.Hero.Pos + Map.I.Hero.GetRelativePosition( EDirection.NW, 1 ) ) + Map.I.Hero.GetRelativePosition( EDirection.N, i );
//Vector2 zf = ( Map.I.Hero.Pos + Map.I.Hero.GetRelativePosition( EDirection.N,  1 ) ) + Map.I.Hero.GetRelativePosition( EDirection.N, i );
//Vector2 zr = ( Map.I.Hero.Pos + Map.I.Hero.GetRelativePosition( EDirection.NE, 1 ) ) + Map.I.Hero.GetRelativePosition( EDirection.N, i );

//Unit ul = Map.I.GetUnit( zl, ELayerType.MONSTER, true );
//Unit uf = Map.I.GetUnit( zf, ELayerType.MONSTER, true );
//Unit ur = Map.I.GetUnit( zr, ELayerType.MONSTER, true );

//if( ul != null && ul.ValidMonster ||
//    uf != null && uf.ValidMonster ||
//    ur != null && ur.ValidMonster )
//{
//    zone = true; break;
//}
//if( !Map.I.PtOnAreaMap( zl ) && Map.I.PtOnAreaMap( zf ) && Map.I.PtOnAreaMap( zr ) ) break;



//		//OriginalHero.gameObject.SetActive( true );
//GameObject instance = (GameObject)GameObject.Instantiate ( OriginalHero.gameObject );
//Hero = I.GetComponent<Unit>();		
//Unit[ (int)pos.x, (int)pos.y ] = Hero.GetComponent<Unit>();
//Hero.Pos = pos;
//Hero.gameObject.name = "Hero";
//OriginalHero.gameObject.SetActive( false );



//if( Mtx != -1 && Map.I.RM.TileArea != null )
//    UI.I.DebugLabel.text += "\nTile Area: " + Map.I.RM.TileArea[ Mtx, Mty] + "\n"; //

//float angle = 0;
//EZone zone = Hero.GetPositionZone( new Vector2( Mtx, Mty ), ref angle );

//Vector2 ms = new Vector2( Mtx, Mty );
//int area = GetPosArea( new Vector2( Mtx, Mty ) );

//if( area != -1 )
//{
//    r = Quest.I.CurLevel.AreaList[ area ].AreaRect;
//    UI.I.DebugLabel.text += "\n\n\nRect: " + " x: " + r.x + " y: " + r.y + " width: " + r.width + " height " + r.height + "\nxMin " + r.xMin + " xMax " + r.xMax + "\nyMin " + r.yMin + " yMax " + r.yMax +
//        "\n Size: " + r.size + " pos: " + r.position + " center: " + r.center + " min: " + r.min + " max: " + r.max;
//}

//if( area != -1 )
//{
//    string opt = "";
//    if( Map.I.CurrentArea != -1 && Map.I.CurArea.Optional ) opt = " - (Optional)";
//    UI.I.DebugLabel.text += "\nLevel: " + ( Quest.CurrentLevel + 1 ) + " - " + Quest.I.CurLevel.AreaList[ area ].AreaName +
//    " (" + Quest.I.CurLevel.AreaList[ area ].P1.x + ", " + Quest.I.CurLevel.AreaList[ area ].P1.y + ")" + opt;
//}

//Camera cam =  Manager.I.Cam.GetComponent<Camera>();
//UI.I.DebugLabel.text += "Cam Pos:" + cam.transform.position.x + " " +cam.transform.position.y + " " + cam.transform.position.z + " \n";
//UI.I.DebugLabel.text += "Cam Rot:" + cam.transform.rotation.x + " " + cam.transform.rotation.y + " " + cam.transform.rotation.z + " \n";
// UI.I.DebugLabel.text += "SamePosTouchTimeCount = " + SamePosTouchTimeCount + " - ButtonPressingTimeCount = " + ButtonPressingTimeCount + "\n";

//UI.I.DebugLabel.text += "Acelerometer: X: " + Input.acceleration.x + "  Y: " + Input.acceleration.y + "  Z:  " + Input.acceleration.z + "\n";

//UI.I.DebugLabel.text += "Path: " + Hero.Control.PathFinding.Path.Count + "\n";
//UI.I.DebugLabel.text += "Down Touch 0: " + SwipeTileOrigin[ 0 ].x + "  " + SwipeTileOrigin[ 0 ].y + "\n";
//UI.I.DebugLabel.text += "Down Touch 1: " + SwipeTileOrigin[ 1 ].x + "  " + SwipeTileOrigin[ 1 ].y + "\n";
//UI.I.DebugLabel.text += "Down Touch 2: " + SwipeTileOrigin[ 2 ].x + "  " + SwipeTileOrigin[ 2 ].y + "\n";

//UI.I.DebugLabel.text += "Up Touch 0: " + SwipeTileDest[ 0 ].x + "  " + SwipeTileDest[ 0 ].y + "\n";
//UI.I.DebugLabel.text += "Up Touch 1: " + SwipeTileDest[ 1 ].x + "  " + SwipeTileDest[ 1 ].y + "\n";
//UI.I.DebugLabel.text += "Up Touch 2: " + SwipeTileDest[ 2 ].x + "  " + SwipeTileDest[ 2 ].y + "\n";

//UI.I.DebugLabel.text += "Down Touch 0: " + SwipeOrigin[ 0 ].x + "  " + SwipeOrigin[ 0 ].y + "\n";
//UI.I.DebugLabel.text += "Down Touch 1: " + SwipeOrigin[ 1 ].x + "  " + SwipeOrigin[ 1 ].y + "\n";
//UI.I.DebugLabel.text += "Down Touch 2: " + SwipeOrigin[ 2 ].x + "  " + SwipeOrigin[ 2 ].y + "\n";

//UI.I.DebugLabel.text += "Up Touch 0: " + SwipeDest[ 0 ].x + "  " + SwipeDest[ 0 ].y + "\n";
//UI.I.DebugLabel.text += "Up Touch 1: " + SwipeDest[ 1 ].x + "  " + SwipeDest[ 1 ].y + "\n";
//UI.I.DebugLabel.text += "Up Touch 2: " + SwipeDest[ 2 ].x + "  " + SwipeDest[ 2 ].y + "\n";


//

//if( TurnData != null )
//	for( int i = 0; i < TurnData.Count; i++ )
//		UI.I.DebugLabel.text += "Turn " + i + " " + TurnData[ i ].Action    + " Time: " + TurnData[ i ].ActionTime.ToString("0.00") + " Pos:" +
//		TurnData[ i ].HeroPos.x + " " + TurnData[ i ].HeroPos.y + " Dir: "  + TurnData[ i ].HeroDir    + "\n";




//Rect r = Quest.I.LevelList[ Quest.I.CurrentLevel ].AreaList[ area ].AreaRect;		// optimize
//AreaOffset = new Vector2( r.x, r.y - r.height + 1 );		
//Vector p1 = new Vector( (int)(r.x), (int)(r.y));
//Vector p2 = new Vector( (int)(r.x + r.width-1), (int)(r.y - r.height + 1));
//
//for ( int y = p2.y; y <= p1.y; y++ )
//	for ( int x = p1.x; x <= p2.x; x++ )
//{
//	if( Unit[ x, y ] != null )
//		if( Unit[ x, y ].ValidMonster )
//			Unit[ x, y ].Kill();
//	
//	if( Gaia[ x, y ] != null )
//		if( Gaia[ x, y ].TileID == ETileType.ROOMDOOR )
//	{
//		int id = Gaia[ x, y ].DoorID;
//		for ( int yy = 0; yy < Tilemap.height; yy++ )
//			for ( int xx = 0; xx < Tilemap.width;  xx++ ) 
//				if  ( Gaia[ xx, yy ] != null )
//					if  ( Gaia[ xx, yy ].TileID == ETileType.ROOMDOOR )
//						if  ( Gaia[ xx, yy ].DoorID == id )
//					{
//						ClearTransTile( xx, yy );
//						SetTile( xx, yy, ELayerType.GAIA, ETileType.NONE);
//					}
//	}
//}
//UpdateTransTilemap = true;











//if( Manager.I.GameType == EGameType.CUBES )     // Dungeon
//{
//    Sector s = Sector.GetPosSector( new Vector2( Mtx, Mty ) );

//    if( s != null )
//    {
//        UI.I.DebugLabel.text += "Sector Pos: " + s.X + " " + s.Y + "\n";
//        UI.I.DebugLabel.text += "Sector Type: " + s.Type + "\n";
//        UI.I.DebugLabel.text += "Sector Area: " + s.Area + "\n";
//        UI.I.DebugLabel.text += "Sector Cleared: " + s.Cleared + "\n";
//        UI.I.DebugLabel.text += "Sector Discovered: " + s.Discovered + "\n";
//    }
//}





